[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

